### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by jeffers81** [pl453s/linux-mint-gnome#1]
native right click terminal isn't opening.

**Comment by pl453s** [comment]
Can you precise the issue?
I can launch 'gnome-terminal' by right-clicking on the desktop or in a 'nautilus' folder.
Did-I misunderstand your issue?
Thanks in advance

**Comment by pl453s** [comment]
Hello,
I'm sorry, but without any answer, I'll have no other choice than close this issue.
I didn't understand what this issue refers to.
I'll wait a bit more before definitely close the issue.

**Comment by jeffers81** [comment]
I reinstalled and everything works fine. My apologies

**Comment by pl453s** [comment]
No problem ;) I close this issue
Thank you for showing interest in my ~~distribution~~ project, by the way!
